### ISSUE TITLE
Add option to link to blog

### ISSUE THREAD

**Issue by maximousblk** [albertocc/feed-box#2]
It would be awesome if there was an option to directly link to the page where everyone can reed the posts. for example, if I have a blog, i would want a link to my blog on the top of the gist

**Comment by albertocc** [comment]
Hi @maximousblk! Sorry for the late response. It would be a great, but unfortunate only plain text is displayed in pinned gists, so it's not possible to include a "clickable link". The only solution I see is to include a comment in the gist with a link to the blog:
 
![image](https://user-images.githubusercontent.com/13858689/95666086-cda27080-0b56-11eb-9245-d6dbd556c611.png)
